version: 2

models:
  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airbnb host details
    columns:
      - name: host_id
        description: Host ID number
        tests:
          - not_null
          - unique

      - name: host_name
        description: Name of host
        tests:
          - not_null

      - name: is_superhost
        description: Boolean value showing superhost status
        tests:
          - accepted_values:
              values: ["t", "f"]

  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50 # (Optional)
              max_value: 500 # (Optional)
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config: 
                severity: warn

  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings
    columns:
      - name: listing_id
        description: Primary key for listing
        tests:
          - unique
          - not_null

      - name: host_id
        description: The host's id. References the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of apartment/room
        tests:
          - accepted_values:
              values:
                ["Entire home/apt", "Private room", "Shared room", "Hotel room"]

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value
